config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("erp/", include('core.erp.urls')),
    path('', index, name='index')
]

core/erp/urls.py
from django.contrib import admin
from django.urls import path
from core.erp.views.category.views import *

app_name = 'erp'

urlpatterns = [
    path("category/list/", CategoryListView.as_view(), name="category_list"),
    path("category/create/",
         CategoryCreateView.as_view(), name="category_create"),
    path("category/update/<int:pk>/",
         CategoryUpdateView.as_view(), name="category_update"),
    path("category/delete/<int:pk>/",
         CategoryDeleteView.as_view(), name="category_delete"),
]

core/erp/models.py
from django.db import models
from datetime import datetime
from django.forms import model_to_dict

from core.erp.choices import gender_choices


class Category(models.Model):
    name = models.CharField(max_length=60, verbose_name='Nombre', unique=True)
    desc = models.TextField(max_length=200, null=True,
                            blank=True, verbose_name='Descripción')

    def __str__(self):
        return self.name

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nombre', unique=True)
    cate = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to='product/%Y/%m/%d', null=True, blank=True)
    pvp = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']


class Client(models.Model):
    names = models.CharField(max_length=150, verbose_name='Nombres')
    surnames = models.CharField(max_length=150, verbose_name='Apellidos')
    dni = models.CharField(max_length=10, unique=True, verbose_name='Dni')
    birthday = models.DateField(
        default=datetime.now, verbose_name='Fecha de nacimiento')
    address = models.CharField(
        max_length=150, null=True, blank=True, verbose_name='Dirección')
    sexo = models.CharField(
        max_length=10, choices=gender_choices, default='male', verbose_name='Sexo')

    def __str__(self):
        return self.names

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['id']


class Sale(models.Model):
    cli = models.ForeignKey(Client, on_delete=models.CASCADE)
    date_joined = models.DateField(default=datetime.now)
    subtotal = models.DecimalField(
        default=0.00, max_digits=9, decimal_places=2)
    iva = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.cli.names

    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'Ventas'
        ordering = ['id']


class DetSale(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    prod = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    cant = models.IntegerField(default=0)
    subtotal = models.DecimalField(
        default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.prod.name

    class Meta:
        verbose_name = 'Detalle de Venta'
        verbose_name_plural = 'Detalle de Ventas'
        ordering = ['id']

core/erp/forms.py
from django import forms
from django.forms import TextInput, Textarea
from core.erp.models import Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'name': TextInput(
                attrs={'placeholder': 'Ingrese el Nombre',
                       'autofocus': True, }
            ),
            'desc': Textarea(
                attrs={'placeholder': 'Ingrese la Descripcion',
                       'rows': 4,
                       'cols': 1, }
            ),
        }
    # def save(self, commit=True):
    #     data = {}
    #     form = super()
    #     try:
    #         if form.is_valid():
    #             form.save()
    #         else:
    #             data['error'] = form.errors
    #     except Exception as e:
    #         data['error'] = str(e)
    #     return data

config/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

core/erp/views/category/views.py
from webbrowser import get
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from core.erp.forms import CategoryForm
from core.erp.models import Category
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator


class CategoryListView(ListView):
    model = Category
    template_name = 'category/list_category.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            data = Category.objects.get(pk=request.POST['id']).toJSON()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Listado de Categorias'
        context["create_url"] = reverse_lazy('erp:category_create')
        context["list_url"] = reverse_lazy('erp:category_list')
        context["entity"] = 'Categorias'
        return context


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'category/create_category.html'
    success_url = reverse_lazy('erp:category_list')

    # def post(self, request, *args, **kwargs):
    #     data = {}
    #     try:
    #         action = request.POST['action']
    #         if action == 'add':
    #             form = self.get_form()
    #             data = form.save()
    #         else:
    #             data['error'] = 'No ha ingresado a ninguna opción'
    #     except Exception as e:
    #         data['error'] = str(e)
    #     return JsonResponse(data)

    #     print(request.POST)
    #     form = CategoryForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         return HttpResponseRedirect(self.success_url)
    #     self.object = None
    #     context = self.get_context_data(**kwargs)
    #     context['form'] = form
    #     return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Creación de Categorias'
        context["list_url"] = reverse_lazy('erp:category_list')
        context["entity"] = 'Categorias'
        # context["action"] = 'add'
        return context


class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = "category/update_category.html"
    success_url = reverse_lazy('erp:category_list')

    # def post(self, request, *args, **kwargs ):


    def get_context_data(self, **kwargs):
        # print(self.object)
        # print(self.get_object())
        context = super().get_context_data(**kwargs)
        context["title"] = 'Edicion de Categoria'
        context["list_url"] = reverse_lazy('erp:category_list')
        context["entity"] = 'Categorias'
        # context["action"] = 'edit'
        return context


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = "category/delete_category.html"
    success_url = reverse_lazy('erp:category_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Eliminación de Categoria'
        context["list_url"] = reverse_lazy('erp:category_list')
        context["entity"] = 'Categorias'
        # context["action"] = 'delete'
        return context

core/erp/templates/category/create_category.html
{% extends 'body.html' %}

{% block content %}
<form method="post" action=".">
  <div class="card card-default">
    <div class="card-header">
      <h3 class="card-title">
        <i class="fas fa-plus"></i>
        {{ title }}
      </h3>
    </div>
    <div class="card-body">
      {% csrf_token %}
      {% for field in form.visible_fields %} 
      <div class="form-group">
        <label for='{{field.label_tag}}' class="form-label">{{field.label}}</label>
        {{field}}
      </div>
      {% endfor %}
      
    </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary btn-flat">
        <i class="fas fa-save"></i> Guardar registro
      </button>
    </div>
  </div>
</form>
{% endblock %}

core/erp/templates/category/delete_category.html
{% extends 'delete.html' %}

core/erp/templates/category/list.html
{% extends 'list.html' %}

{% block columns %}
    <tr>
        <th scope="col">Nro</th>
        <th scope="col">Nombre</th>
        <th scope="col">Opciones</th>
    </tr>
{% endblock %}

{% block rows %}
    {% for c in categories %}
        <tr>
            <td>{{ c.id }}</td>
            <td>{{ c.name }}</td>
            <td>
                <button type="button" class="btn btn-warning btn-xs btn-flat">
                    <i class="fas fa-edit">  Editar</i>
                    
                </button>
                <button type="button" class="btn btn-danger btn-xs btn-flat">
                    <i class="fas fa-trash-alt">  Borrar</i>
                </button>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

core/erp/templates/category/list_category.html
{% extends 'list.html' %}

{% block columns %}
    <tr>
        <th scope="col" style="width:10%">Nro</th>
        <th scope="col" style="width:70%">Nombre</th>
        <th scope="col" style="width:20%">Opciones</th>
    </tr>
{% endblock %}


{% block rows %}
    {% for c in object_list %}
        <tr>
            <td>{{ c.id }}</td>
            <td>{{ c.name }}</td>
            <td>
                <a href="{% url 'erp:category_update' c.id %}" type="button" class="btn btn-warning btn-xs btn-flat">
                    <i class="fas fa-edit"></i>
                    
                </a>
                <a href="{% url 'erp:category_delete' c.id %}" type="button" class="btn btn-danger btn-xs btn-flat">
                    <i class="fas fa-trash-alt"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

core/erp/templates/category/update_category.html
{% extends 'form.html' %}

templates/body.html
{% extends 'home.html' %}
{% block body %}

<body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    {% block javascript %}
    {% endblock javascript %}
</body>
{% endblock %}

templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}

{% block content %}
<form method="post" action=".">
  <div class="card card-default">
    <div class="card-header">
      <h3 class="card-title">
        <i class="fas fa-delete"></i>
        {{ title }}
      </h3>
    </div>
    <div class="card-body">
      {% csrf_token %}
      <input type="hidden" name="action" value="{{ action }}">

      {% if form.errors %}
      <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-ban"></i> Error al Guardar el registro</h5>
        <ul>
          {% for field in form %}
          {% for error in field.errors %}
          <li>{{error}}</li>
          {% endfor %}
          {% endfor %}
        </ul>
      </div>
      {% endif %}
      <div class="alert alert-danger alert-dismissible">
        <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
        Estas seguro de eliminar el registro {{ object}} ?
        </div>
    </div>
   
    <div class="card-footer">
      <button type="submit" class="btn btn-primary btn-flat">
        <i class="fas fa-save"></i> Aceptar
      </button>
      <a href="{{ list_url }}" class="btn btn-info btn-flat">
        <i class="fas fa-times"></i> Cancelar
      </a>
    </div>
  </div>
</form>


{% endblock %}

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

templates/form.html
{% extends 'body.html' %}
{% load widget_tweaks %}

{% block content %}
<form method="post" action=".">
  <div class="card card-default">
    <div class="card-header">
      <h3 class="card-title">
        <i class="fas fa-plus"></i>
        {{ title }}
      </h3>
    </div>
    <div class="card-body">
      {% csrf_token %}
      <input type="hidden" name="action" value="{{ action }}">

      {% if form.errors %}
      <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fas fa-ban"></i> Error al Guardar el registro</h5>
        <ul>
          {% for field in form %}
          {% for error in field.errors %}
          <li>{{error}}</li>
          {% endfor %}
          {% endfor %}
        </ul>
      </div>
      {% endif %}

      {% for field in form.visible_fields %}
      <div class="form-group">
        <label for='{{field.label_tag}}' class="form-label">{{field.label}}</label>
        {{field|add_class:'form-control'|attr:'autocomplete:off'}}
      </div>
      {% endfor %}

    </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary btn-flat">
        <i class="fas fa-save"></i> Guardar registro
      </button>
    </div>
  </div>
</form>
<!--
<script>
  
  {% if form.errors %}
      var errors = '';
      {% for field in form %}
          {% for error in field.errors %}
              errors += '{{ error }}\n';
          {% endfor %}
      {% endfor %}
      Swal.fire({
          title: 'Error!!',
          text: errors,
          icon: 'error'
      });
  {% endif %}
  
  $('form').on('submit', function (e) {
    e.preventDefault();
    var parameters = $(this).serializeArray();
  
    $.ajax({
        url: '{% url 'erp:category_create' %}',
        type: 'POST',
        data: parameters,
        dataType: 'json'
    }).done(function (data) {
        if (!data.hasOwnProperty('error')) {
            location.href = '{{ list_url }}';
            return false;
        }
        message_error(data.error);
    }).fail(function (jqXHR, textStatus, errorThrown) {
        alert(textStatus + ': ' + errorThrown);
    }).always(function (data) {

    });
  
  });
 
</script>
-->
{% endblock %}

templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
        <a href="#" class="navbar-brand">
            <img src="{% static 'img/logo.png' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Hades</span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'index' %}" class="nav-link"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'erp:category_list' %}" class="dropdown-item"><i class="fas fa-truck-loading"></i> Categorías</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-boxes"></i> Productos</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-users"></i> Clientes</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Ventas</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-bell"></i>
                    <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">15 Notifications</span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-envelope mr-2"></i> 4 new messages
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-users mr-2"></i> 8 friend requests
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-file mr-2"></i> 3 new reports
                        <span class="float-right text-muted text-sm">2 days</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }}</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.2.0/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    {% block head %}
    {% endblock head %}
</head>
{% block body %}

{% endblock %}
</html>

templates/index.html
{% extends 'body.html' %}

{% block content %}
<h1 class="text-primary">Home Page</h1>
{% endblock %}

templates/list.html
{% extends 'body.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}" />
<link rel="stylesheet"
  href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}" />
<script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
{% endblock head %}

{% block content %}
<div class="card card-default">
  <div class="card-header">
    <h3 class="card-title">
      <i class="fas fa-list"></i>
      {{ title }}
    </h3>
  </div>
</div>
<div class="card-body">
  <table class="table" id="data">
    <thead>
      {% block columns %}

      {% endblock %}
    </thead>
    <tbody>
      {% block rows %}

      {% endblock %}
    </tbody>
  </table>
</div>
<div class="card-footer">
  <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
    <i class="fas fa-plus"></i> Nuevo registro
  </a>
</div>

</div>
{% endblock content %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });
            $('.btnTest').on('click', function () {
              $.ajax({
                  url: '{% url 'erp:category_list' %}',
                  type: 'POST',
                  data: {id: 1},
                  dataType: 'json'
              }).done(function (data) {
                  console.log(data);
              }).fail(function (jqXHR, textStatus, errorThrown) {
                  alert(textStatus+': '+errorThrown);
              }).always(function (data) {

              });
            });
        });
    </script>
{% endblock javascript %}

templates/second.html
{% extends 'index.html' %}

{% block content %}

    <a href="{% url 'erp:vista2' %}">Click</a>

    <ul>
        {% for product in products %}
            <li>{{ product.id }} / {{ product.name }} / {{ product.cate.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}